<?php

namespace Moneris\MonerisCheckout\Block\Payment;

class Info extends \Magento\Payment\Block\Info
{
    public function getSpecificInformation() {
        $info = $this->getInfo();
        $specs = [];

        foreach ([
            'moneris_checkout_transaction_date_time' => (string)__('Transaction Date'),
            'moneris_checkout_transaction_no' => (string)__('Transaction Number'),
            'moneris_checkout_order_no' => (string)__('Reference Number'),
            ] as $key => $value) {
            if (!empty($info->getAdditionalInformation($key))) {
                $specs[$value] = $info->getAdditionalInformation($key);
            }
        }


        return $specs;
    }

    public function getMethod() {
        return parent::getMethod(); // TODO: Change the autogenerated stub
    }
}
